# Generated by Django 4.1.3 on 2023-05-22 09:19

import budget.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0003_alter_income_options_alter_moneybox_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categoryincome",
            options={
                "verbose_name": "Категория дохода",
                "verbose_name_plural": "Категориb дохода",
            },
        ),
        migrations.AlterField(
            model_name="categoryincome",
            name="description",
            field=models.TextField(
                blank=True,
                max_length=500,
                verbose_name="Комментарий к категории дохода",
            ),
        ),
        migrations.AlterField(
            model_name="categoryincome",
            name="title",
            field=models.CharField(max_length=150, verbose_name="Название категории"),
        ),
        migrations.AlterField(
            model_name="income",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                validators=[budget.models.validate_date],
                verbose_name="Время создания записи",
            ),
        ),
        migrations.AlterField(
            model_name="income",
            name="description",
            field=models.TextField(
                blank=True, max_length=500, verbose_name="Комментарий к приходу"
            ),
        ),
        migrations.AddConstraint(
            model_name="categoryincome",
            constraint=models.UniqueConstraint(
                fields=("title", "user"), name="unique_title_user"
            ),
        ),
    ]
