# Generated by Django 4.1.3 on 2023-05-22 17:05

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0004_alter_categoryincome_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF",
                image_field=None,
                max_length=7,
                samples=None,
                verbose_name="HEX-код цвета",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.ImageField(
                blank=True, upload_to="icons_category", verbose_name="Иконка категории"
            ),
        ),
        migrations.AddField(
            model_name="categoryincome",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF",
                image_field=None,
                max_length=7,
                samples=None,
                verbose_name="HEX-код цвета",
            ),
        ),
        migrations.AddField(
            model_name="categoryincome",
            name="icon",
            field=models.ImageField(
                blank=True, upload_to="icons_category", verbose_name="Иконка категории"
            ),
        ),
    ]
